openapi: 3.0.0
info:
  title: Not used API
  description: Just here to generate model of the thalweg engine
  version: 2024.01.01
paths:
  /fake:
    get:
      summary: Fake path to be valid against openapi 3.0.0
      responses:
        '200':
          description: fake response to be valid against openapi 3.0.0
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThalwegGameConfiguration'
components:
  schemas:
    Color:
      type: object
      properties:
        r:
          type: number
          default: 1
          format: float
        g:
          type: number
          default: 1
          format: float
        b:
          type: number
          default: 1
          format: float
        a:
          type: number
          default: 1
          format: float
    FontConfig:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/FontName'
        source:
          type: string
          pattern: ^font/.*\.(ttf)$
        size:
          type: integer
          format: int32
          default: 12
        xAdjust:
          type: number
          format: float
          default: 0
        yAdjust:
          type: number
          format: float
          default: 0
        widthAdjust:
          type: number
          format: float
          default: 0
        heightAdjust:
          type: number
          format: float
          default: 0
      required:
        - name
        - source
    FontConfigs:
      type: object
      properties:
        family:
          type: array
          items:
            $ref: '#/components/schemas/FontConfig'
        vars:
          $ref: '#/components/schemas/Vars'
    FontName:
      type: string
      description: "The name to retrieve the font. It should be unique. Use 'default' to override the default font."
    GdxConfiguration:
      type: object
      properties:
        logLevel:
          $ref: '#/components/schemas/LogLevelEnum'
    Interpolation:
      type: string
      enum:
        - LINEAR
        - POW
      default: LINEAR
    LogLevelEnum:
      type: string
      enum:
        - DEBUG
        - INFO
        - ERROR
        - NONE
    LogTask:
      allOf:
        - $ref: '#/components/schemas/Task'
        - properties:
            message:
              type: string
              description: The message to log
      required:
        - type
        - message
    Lwjgl3ApplicationConfig:
      type: object
      properties:
        title:
          type: string
          default: My Thalweg Game
        windowed:
          $ref: '#/components/schemas/WidthAndHeight'
        useVSync:
          type: boolean
          default: true
        foregroundFPS:
          type: integer
          default: 60
          minimum: 0
    OverTimeTask:
      allOf:
        - $ref: '#/components/schemas/Task'
        - properties:
            duration:
              type: number
              format: float
              description: The duration in seconds
              default: 0
            interpolation:
              $ref: '#/components/schemas/Interpolation'
            delay:
              type: number
              format: float
              description: The time to wait before starting the action
              default: 0
    ParallelTask:
      type: object
      allOf:
        - $ref: '#/components/schemas/TaskArray'
    PlayTransitionTask:
      allOf:
        - $ref: '#/components/schemas/OverTimeTask'
        - properties:
            transition:
              type: string
              pattern: ^transition/.*\.(png)$
              description: Name of the transition
    Position:
      type: object
      description: A position, with coordinate in world system
      properties:
        x:
          type: number
          format: float
          default: 0
        y:
          type: number
          format: float
          default: 0
        z:
          type: integer
          default: 0
    SetCursorTask:
      allOf:
        - $ref: '#/components/schemas/Task'
        - properties:
            cursor:
              type: string
              pattern: ^cursor/.*\.(ttf)$
            xHotspot:
              type: integer
              format: int32
              default: 0
              description: Position on the X-Axis of the active pixel
            yHotspot:
              type: integer
              format: int32
              default: 0
              description: Position on the Y-Axis of the active pixel
      required:
        - type
        - cursor
    Scale:
      type: object
      properties:
        x:
          type: number
          format: float
          default: 1
        y:
          type: number
          format: float
          default: 1
    SequenceTask:
      type: object
      allOf:
        - $ref: '#/components/schemas/TaskArray'
    SetMouseLabelTask:
      allOf:
        - $ref: '#/components/schemas/Task'
        - properties:
            label:
              type: string
              description: The text to display near the mouse
            fontName:
              $ref: '#/components/schemas/FontName'
      required:
        - type
        - label
    Task:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/TaskTypeEnum'
      required:
        - type
      discriminator:
        propertyName: type
        mapping:
          LOG: '#/components/schemas/LogTask'
          PARALLEL: '#/components/schemas/ParallelTask'
          PLAY_TRANSITION: '#/components/schemas/PlayTransitionTask'
          SEQUENCE: '#/components/schemas/SequenceTask'
          SET_CURSOR: '#/components/schemas/SetCursorTask'
          SET_MOUSE_LABEL: '#/components/schemas/SetMouseLabelTask'
          WAIT: '#/components/schemas/OverTimeTask'
    TaskArray:
      allOf:
        - $ref: '#/components/schemas/Task'
        - properties:
            todos:
              type: array
              items:
                $ref: '#/components/schemas/Task'
      required:
        - type
        - todos
    TaskTypeEnum:
      enum:
        - LOG
        - PARALLEL
        - PLAY_TRANSITION
        - SEQUENCE
        - SET_CURSOR
        - SET_MOUSE_LABEL
        - WAIT
    ThalwegActor:
      type: object
      properties:
        position:
          $ref: '#/components/schemas/Position'
        scale:
          $ref: '#/components/schemas/Scale'
        texture:
          type: string
        vertices:
          type: array
          items:
            $ref: '#/components/schemas/XY'
        triggers:
          type: array
          items:
            $ref: '#/components/schemas/Trigger'
    ThalwegGameConfiguration:
      type: object
      properties:
        debug:
          type: boolean
          default: false
        gdx:
          $ref: '#/components/schemas/GdxConfiguration'
        lwjgl3ApplicationConfig:
          $ref: '#/components/schemas/Lwjgl3ApplicationConfig'
        startScreen:
          type: string
          pattern: ^screen/.*\.(json|yaml)$
        world:
          $ref: '#/components/schemas/World'
      required:
        - debug
        - startScreen
        - world
    ThalwegScreen:
      type: object
      properties:
        name:
          type: string
        actors:
          type: array
          items:
            $ref: '#/components/schemas/ThalwegActor'
      required:
        - name
        - actors
    Trigger:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/TriggerTypeEnum'
        todo:
          $ref: '#/components/schemas/Task'
    TriggerTypeEnum:
      type: string
      enum:
        - AUTO
        - MOUSEENTER
        - MOUSELEAVE
    CustomVar:
      type: object
      properties:
        name:
          type: string
        value:
          type: string
      required:
        - name
        - value
    Vars:
      type: object
      properties:
        existing:
          type: object
          properties:
            mouseLabelDefaultToken:
              type: string
        custom:
          type: array
          items:
            $ref: '#/components/schemas/CustomVar'
    WidthAndHeight:
      type: object
      properties:
        width:
          type: integer
          minimum: 0
          default: 0
        height:
          type: integer
          minimum: 0
          default: 0
      required:
        - width
        - height
    World:
      allOf:
        - $ref: '#/components/schemas/WidthAndHeight'
    XY:
      type: object
      properties:
        x:
          type: number
          format: float
          default: 0
        y:
          type: number
          format: float
          default: 0