/*
 * Not used API
 * Just here to generate model of the thalweg engine
 *
 * The version of the OpenAPI document: 2024.01.01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.thalweg.engine.infra.data.task;

import lombok.Getter;

/**
 * Gets or Sets TaskTypeEnum
 */
@Getter
public enum TaskTypeEnumData {

    LOG("LOG", LogTaskData.class),

    PARALLEL("PARALLEL", ParallelTaskData.class),

    PLAY_TRANSITION("PLAY_TRANSITION", PlayTransitionTaskData.class),

    SEQUENCE("SEQUENCE", SequenceTaskData.class),

    SET_CURSOR("SET_CURSOR", SetCursorTaskData.class),

    SET_MOUSE_LABEL("SET_MOUSE_LABEL", SetMouseLabelTaskData.class),

    WAIT("WAIT", WaitTaskData.class);

    private final String value;

    private final Class<? extends TaskData> target;

    TaskTypeEnumData(String value, Class<? extends TaskData> target) {
        this.value = value;
        this.target = target;
    }
}

