/*
 * Not used API
 * Just here to generate model of the thalweg engine
 *
 * The version of the OpenAPI document: 2024.01.01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.thalweg.engine.infra.data;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.mapstruct.Mapper;
import org.mapstruct.control.DeepClone;
import org.mapstruct.factory.Mappers;

import java.util.Objects;

/**
 * GdxConfigurationData
 */
@JsonPropertyOrder({
        GdxConfigurationData.JSON_PROPERTY_LOG_LEVEL
})
@JsonTypeName("GdxConfiguration")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GdxConfigurationData {
    public static final String JSON_PROPERTY_LOG_LEVEL = "logLevel";
    public LogLevelEnumData logLevel;

    public GdxConfigurationData() {
    }

    public GdxConfigurationData logLevel(LogLevelEnumData logLevel) {

        this.logLevel = logLevel;
        return this;
    }

    /**
     * Get logLevel
     *
     * @return logLevel
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LOG_LEVEL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public LogLevelEnumData getLogLevel() {
        return logLevel;
    }


    @JsonProperty(JSON_PROPERTY_LOG_LEVEL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLogLevel(LogLevelEnumData logLevel) {
        this.logLevel = logLevel;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GdxConfigurationData gdxConfiguration = (GdxConfigurationData) o;
        return Objects.equals(this.logLevel, gdxConfiguration.logLevel);
    }

    @Override
    public int hashCode() {
        return Objects.hash(logLevel);
    }

    @Override
    public String toString() {
        String sb = "class GdxConfigurationData {\n" +
                "    logLevel: " + toIndentedString(logLevel) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public GdxConfigurationData copy() {
        return Cloner.INSTANCE.clone(this);
    }

    @Mapper(mappingControl = DeepClone.class)
    public interface Cloner {
        Cloner INSTANCE = Mappers.getMapper(Cloner.class);

        GdxConfigurationData clone(GdxConfigurationData source);


    }

}

