/*
 * Not used API
 * Just here to generate model of the thalweg engine
 *
 * The version of the OpenAPI document: 2024.01.01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.thalweg.engine.infra.data;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets LogLevelEnum
 */
public enum LogLevelEnumData {

    DEBUG("DEBUG"),

    INFO("INFO"),

    ERROR("ERROR"),

    NONE("NONE");

    private final String value;

    LogLevelEnumData(String value) {
        this.value = value;
    }

    @JsonCreator
    public static LogLevelEnumData fromValue(String value) {
        for (LogLevelEnumData b : LogLevelEnumData.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}

