/*
 * Not used API
 * Just here to generate model of the thalweg engine
 *
 * The version of the OpenAPI document: 2024.01.01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.thalweg.engine.infra.data;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.mapstruct.Mapper;
import org.mapstruct.control.DeepClone;
import org.mapstruct.factory.Mappers;

import java.util.Objects;

/**
 * A position, with coordinate in world system
 */
@JsonPropertyOrder({
        PositionData.JSON_PROPERTY_X,
        PositionData.JSON_PROPERTY_Y,
        PositionData.JSON_PROPERTY_Z
})
@JsonTypeName("Position")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PositionData {
    public static final String JSON_PROPERTY_X = "x";
    public static final String JSON_PROPERTY_Y = "y";
    public static final String JSON_PROPERTY_Z = "z";
    public float x = 0f;
    public float y = 0f;
    public int z = 0;

    public PositionData() {
    }

    public PositionData x(float x) {

        this.x = x;
        return this;
    }

    /**
     * Get x
     *
     * @return x
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_X)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public float getX() {
        return x;
    }


    @JsonProperty(JSON_PROPERTY_X)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setX(float x) {
        this.x = x;
    }


    public PositionData y(float y) {

        this.y = y;
        return this;
    }

    /**
     * Get y
     *
     * @return y
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_Y)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public float getY() {
        return y;
    }


    @JsonProperty(JSON_PROPERTY_Y)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setY(float y) {
        this.y = y;
    }


    public PositionData z(int z) {

        this.z = z;
        return this;
    }

    /**
     * Get z
     *
     * @return z
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_Z)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public int getZ() {
        return z;
    }


    @JsonProperty(JSON_PROPERTY_Z)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setZ(int z) {
        this.z = z;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PositionData position = (PositionData) o;
        return Objects.equals(this.x, position.x) &&
                Objects.equals(this.y, position.y) &&
                Objects.equals(this.z, position.z);
    }

    @Override
    public int hashCode() {
        return Objects.hash(x, y, z);
    }

    @Override
    public String toString() {
        String sb = "class PositionData {\n" +
                "    x: " + toIndentedString(x) + "\n" +
                "    y: " + toIndentedString(y) + "\n" +
                "    z: " + toIndentedString(z) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public PositionData copy() {
        return Cloner.INSTANCE.clone(this);
    }

    @Mapper(mappingControl = DeepClone.class)
    public interface Cloner {
        Cloner INSTANCE = Mappers.getMapper(Cloner.class);

        PositionData clone(PositionData source);


    }

}

