/*
 * Not used API
 * Just here to generate model of the thalweg engine
 *
 * The version of the OpenAPI document: 2024.01.01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.thalweg.engine.infra.data;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.mapstruct.Mapper;
import org.mapstruct.control.DeepClone;
import org.mapstruct.factory.Mappers;

public class SetMouseLabelTaskData extends OverTimeTaskData {
    public static final String JSON_PROPERTY_LABEL = "label";
    public static final String JSON_PROPERTY_FONT_NAME = "fontName";
    public String label;
    public String fontName;

    public SetMouseLabelTaskData() {
        super();
    }

    public SetMouseLabelTaskData label(String label) {

        this.label = label;
        return this;
    }

    /**
     * The text to display near the mouse
     *
     * @return label
     **/
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_LABEL)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getLabel() {
        return label;
    }


    @JsonProperty(JSON_PROPERTY_LABEL)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setLabel(String label) {
        this.label = label;
    }


    public SetMouseLabelTaskData fontName(String fontName) {

        this.fontName = fontName;
        return this;
    }

    /**
     * The name to retrieve the font. It should be unique. Use &#39;default&#39; to override the default font.
     *
     * @return fontName
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_FONT_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getFontName() {
        return fontName;
    }


    @JsonProperty(JSON_PROPERTY_FONT_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFontName(String fontName) {
        this.fontName = fontName;
    }

    public SetMouseLabelTaskData copy() {
        return Cloner.INSTANCE.clone(this);
    }

    @Mapper(mappingControl = DeepClone.class)
    public interface Cloner {
        Cloner INSTANCE = Mappers.getMapper(Cloner.class);

        SetMouseLabelTaskData clone(SetMouseLabelTaskData source);


    }

}

