/*
 * Not used API
 * Just here to generate model of the thalweg engine
 *
 * The version of the OpenAPI document: 2024.01.01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.thalweg.engine.infra.data;

import com.badlogic.gdx.utils.Array;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.mapstruct.Mapper;
import org.mapstruct.control.DeepClone;
import org.mapstruct.factory.Mappers;

import java.util.Objects;

/**
 * ThalwegActorData
 */
@JsonPropertyOrder({
        ThalwegActorData.JSON_PROPERTY_POSITION,
        ThalwegActorData.JSON_PROPERTY_SCALE,
        ThalwegActorData.JSON_PROPERTY_TEXTURE,
        ThalwegActorData.JSON_PROPERTY_VERTICES,
        ThalwegActorData.JSON_PROPERTY_TRIGGERS
})
@JsonTypeName("ThalwegActor")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ThalwegActorData {
    public static final String JSON_PROPERTY_POSITION = "position";
    public static final String JSON_PROPERTY_SCALE = "scale";
    public static final String JSON_PROPERTY_TEXTURE = "texture";
    public static final String JSON_PROPERTY_VERTICES = "vertices";
    public static final String JSON_PROPERTY_TRIGGERS = "triggers";
    public PositionData position;
    public ScaleData scale;
    public String texture;
    public Array<XYData> vertices;
    public Array<TriggerData> triggers;

    public ThalwegActorData() {
    }

    public ThalwegActorData position(PositionData position) {

        this.position = position;
        return this;
    }

    /**
     * Get position
     *
     * @return position
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_POSITION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public PositionData getPosition() {
        return position;
    }


    @JsonProperty(JSON_PROPERTY_POSITION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPosition(PositionData position) {
        this.position = position;
    }


    public ThalwegActorData scale(ScaleData scale) {

        this.scale = scale;
        return this;
    }

    /**
     * Get scale
     *
     * @return scale
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SCALE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public ScaleData getScale() {
        return scale;
    }


    @JsonProperty(JSON_PROPERTY_SCALE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setScale(ScaleData scale) {
        this.scale = scale;
    }


    public ThalwegActorData texture(String texture) {

        this.texture = texture;
        return this;
    }

    /**
     * Get texture
     *
     * @return texture
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TEXTURE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getTexture() {
        return texture;
    }


    @JsonProperty(JSON_PROPERTY_TEXTURE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTexture(String texture) {
        this.texture = texture;
    }


    public ThalwegActorData vertices(Array<XYData> vertices) {

        this.vertices = vertices;
        return this;
    }

    public ThalwegActorData addVerticesItem(XYData verticesItem) {
        if (this.vertices == null) {
            this.vertices = new Array<>();
        }
        this.vertices.add(verticesItem);
        return this;
    }

    /**
     * Get vertices
     *
     * @return vertices
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_VERTICES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Array<XYData> getVertices() {
        return vertices;
    }


    @JsonProperty(JSON_PROPERTY_VERTICES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVertices(Array<XYData> vertices) {
        this.vertices = vertices;
    }


    public ThalwegActorData triggers(Array<TriggerData> triggers) {

        this.triggers = triggers;
        return this;
    }

    public ThalwegActorData addTriggersItem(TriggerData triggersItem) {
        if (this.triggers == null) {
            this.triggers = new Array<>();
        }
        this.triggers.add(triggersItem);
        return this;
    }

    /**
     * Get triggers
     *
     * @return triggers
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TRIGGERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Array<TriggerData> getTriggers() {
        return triggers;
    }


    @JsonProperty(JSON_PROPERTY_TRIGGERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTriggers(Array<TriggerData> triggers) {
        this.triggers = triggers;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ThalwegActorData thalwegActor = (ThalwegActorData) o;
        return Objects.equals(this.position, thalwegActor.position) &&
                Objects.equals(this.scale, thalwegActor.scale) &&
                Objects.equals(this.texture, thalwegActor.texture) &&
                Objects.equals(this.vertices, thalwegActor.vertices) &&
                Objects.equals(this.triggers, thalwegActor.triggers);
    }

    @Override
    public int hashCode() {
        return Objects.hash(position, scale, texture, vertices, triggers);
    }

    @Override
    public String toString() {
        String sb = "class ThalwegActorData {\n" +
                "    position: " + toIndentedString(position) + "\n" +
                "    scale: " + toIndentedString(scale) + "\n" +
                "    texture: " + toIndentedString(texture) + "\n" +
                "    vertices: " + toIndentedString(vertices) + "\n" +
                "    triggers: " + toIndentedString(triggers) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public ThalwegActorData copy() {
        return Cloner.INSTANCE.clone(this);
    }

    @Mapper(mappingControl = DeepClone.class)
    public interface Cloner {
        Cloner INSTANCE = Mappers.getMapper(Cloner.class);

        ThalwegActorData clone(ThalwegActorData source);


        default PositionData mapPositionData(PositionData source) {
            return PositionData.Cloner.INSTANCE.clone(source);
        }

        default ScaleData mapScaleData(ScaleData source) {
            return ScaleData.Cloner.INSTANCE.clone(source);
        }

        default Array<XYData> mapXYData(Array<XYData> source) {
            if (source == null) {
                return null;
            }
            var res = new Array<>(source.size);
            for (XYData t : source.toArray())
                res.add(XYData.Cloner.INSTANCE.clone(t));
            return new Array<>(source);
        }

        default Array<TriggerData> mapTriggerData(Array<TriggerData> source) {
            if (source == null) {
                return null;
            }
            var res = new Array<>(source.size);
            for (TriggerData t : source.toArray())
                res.add(TriggerData.Cloner.INSTANCE.clone(t));
            return new Array<>(source);
        }
    }

}

