/*
 * Not used API
 * Just here to generate model of the thalweg engine
 *
 * The version of the OpenAPI document: 2024.01.01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.thalweg.engine.infra.data;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.mapstruct.Mapper;
import org.mapstruct.control.DeepClone;
import org.mapstruct.factory.Mappers;

import java.util.Objects;

/**
 * ThalwegGameConfigurationData
 */
@JsonPropertyOrder({
        ThalwegGameConfigurationData.JSON_PROPERTY_DEBUG,
        ThalwegGameConfigurationData.JSON_PROPERTY_GDX,
        ThalwegGameConfigurationData.JSON_PROPERTY_LWJGL3_APPLICATION_CONFIG,
        ThalwegGameConfigurationData.JSON_PROPERTY_START_SCREEN,
        ThalwegGameConfigurationData.JSON_PROPERTY_WORLD
})
@JsonTypeName("ThalwegGameConfiguration")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ThalwegGameConfigurationData {
    public static final String JSON_PROPERTY_DEBUG = "debug";
    public static final String JSON_PROPERTY_GDX = "gdx";
    public static final String JSON_PROPERTY_LWJGL3_APPLICATION_CONFIG = "lwjgl3ApplicationConfig";
    public static final String JSON_PROPERTY_START_SCREEN = "startScreen";
    public static final String JSON_PROPERTY_WORLD = "world";
    public Boolean debug = false;
    public GdxConfigurationData gdx;
    public Lwjgl3ApplicationConfigData lwjgl3ApplicationConfig;
    public String startScreen;
    public WorldData world;

    public ThalwegGameConfigurationData() {
    }

    public ThalwegGameConfigurationData debug(Boolean debug) {

        this.debug = debug;
        return this;
    }

    /**
     * Get debug
     *
     * @return debug
     **/
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_DEBUG)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public Boolean isDebug() {
        return debug;
    }


    @JsonProperty(JSON_PROPERTY_DEBUG)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setDebug(Boolean debug) {
        this.debug = debug;
    }


    public ThalwegGameConfigurationData gdx(GdxConfigurationData gdx) {

        this.gdx = gdx;
        return this;
    }

    /**
     * Get gdx
     *
     * @return gdx
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_GDX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public GdxConfigurationData getGdx() {
        return gdx;
    }


    @JsonProperty(JSON_PROPERTY_GDX)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setGdx(GdxConfigurationData gdx) {
        this.gdx = gdx;
    }


    public ThalwegGameConfigurationData lwjgl3ApplicationConfig(Lwjgl3ApplicationConfigData lwjgl3ApplicationConfig) {

        this.lwjgl3ApplicationConfig = lwjgl3ApplicationConfig;
        return this;
    }

    /**
     * Get lwjgl3ApplicationConfig
     *
     * @return lwjgl3ApplicationConfig
     **/
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LWJGL3_APPLICATION_CONFIG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Lwjgl3ApplicationConfigData getLwjgl3ApplicationConfig() {
        return lwjgl3ApplicationConfig;
    }


    @JsonProperty(JSON_PROPERTY_LWJGL3_APPLICATION_CONFIG)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLwjgl3ApplicationConfig(Lwjgl3ApplicationConfigData lwjgl3ApplicationConfig) {
        this.lwjgl3ApplicationConfig = lwjgl3ApplicationConfig;
    }


    public ThalwegGameConfigurationData startScreen(String startScreen) {

        this.startScreen = startScreen;
        return this;
    }

    /**
     * Get startScreen
     *
     * @return startScreen
     **/
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_START_SCREEN)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public String getStartScreen() {
        return startScreen;
    }


    @JsonProperty(JSON_PROPERTY_START_SCREEN)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setStartScreen(String startScreen) {
        this.startScreen = startScreen;
    }


    public ThalwegGameConfigurationData world(WorldData world) {

        this.world = world;
        return this;
    }

    /**
     * Get world
     *
     * @return world
     **/
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_WORLD)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public WorldData getWorld() {
        return world;
    }


    @JsonProperty(JSON_PROPERTY_WORLD)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setWorld(WorldData world) {
        this.world = world;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ThalwegGameConfigurationData thalwegGameConfiguration = (ThalwegGameConfigurationData) o;
        return Objects.equals(this.debug, thalwegGameConfiguration.debug) &&
                Objects.equals(this.gdx, thalwegGameConfiguration.gdx) &&
                Objects.equals(this.lwjgl3ApplicationConfig, thalwegGameConfiguration.lwjgl3ApplicationConfig) &&
                Objects.equals(this.startScreen, thalwegGameConfiguration.startScreen) &&
                Objects.equals(this.world, thalwegGameConfiguration.world);
    }

    @Override
    public int hashCode() {
        return Objects.hash(debug, gdx, lwjgl3ApplicationConfig, startScreen, world);
    }

    @Override
    public String toString() {
        String sb = "class ThalwegGameConfigurationData {\n" +
                "    debug: " + toIndentedString(debug) + "\n" +
                "    gdx: " + toIndentedString(gdx) + "\n" +
                "    lwjgl3ApplicationConfig: " + toIndentedString(lwjgl3ApplicationConfig) + "\n" +
                "    startScreen: " + toIndentedString(startScreen) + "\n" +
                "    world: " + toIndentedString(world) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public ThalwegGameConfigurationData copy() {
        return Cloner.INSTANCE.clone(this);
    }

    @Mapper(mappingControl = DeepClone.class)
    public interface Cloner {
        Cloner INSTANCE = Mappers.getMapper(Cloner.class);

        ThalwegGameConfigurationData clone(ThalwegGameConfigurationData source);


        default GdxConfigurationData mapGdxConfigurationData(GdxConfigurationData source) {
            return GdxConfigurationData.Cloner.INSTANCE.clone(source);
        }

        default Lwjgl3ApplicationConfigData mapLwjgl3ApplicationConfigData(Lwjgl3ApplicationConfigData source) {
            return Lwjgl3ApplicationConfigData.Cloner.INSTANCE.clone(source);
        }

        default WorldData mapWorldData(WorldData source) {
            return WorldData.Cloner.INSTANCE.clone(source);
        }
    }

}

