/*
 * Not used API
 * Just here to generate model of the thalweg engine
 *
 * The version of the OpenAPI document: 2024.01.01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.thalweg.engine.infra.data;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.Getter;

@Getter
public enum TriggerTypeEnumData {

    AUTO("AUTO", AutoTriggerData.class),

    MOUSEENTER("MOUSEENTER", MouseEnterTriggerData.class),

    MOUSELEAVE("MOUSELEAVE", MouseLeaveTriggerData.class);

    private final String value;

    private final Class<? extends TriggerData> target;

    TriggerTypeEnumData(String value, Class<? extends TriggerData> target) {
        this.value = value;
        this.target = target;
    }

    @JsonCreator
    public static TriggerTypeEnumData fromValue(String value) {
        for (TriggerTypeEnumData b : TriggerTypeEnumData.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    @JsonValue
    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }
}

