/*
 * Not used API
 * Just here to generate model of the thalweg engine
 *
 * The version of the OpenAPI document: 2024.01.01
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.thalweg.engine.infra.data;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.mapstruct.Mapper;
import org.mapstruct.control.DeepClone;
import org.mapstruct.factory.Mappers;

import java.util.Objects;

/**
 * WidthAndHeightData
 */
@JsonPropertyOrder({
        WidthAndHeightData.JSON_PROPERTY_WIDTH,
        WidthAndHeightData.JSON_PROPERTY_HEIGHT
})
@JsonTypeName("WidthAndHeight")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class WidthAndHeightData {
    public static final String JSON_PROPERTY_WIDTH = "width";
    public static final String JSON_PROPERTY_HEIGHT = "height";
    public int width = 0;
    public int height = 0;

    public WidthAndHeightData() {
    }

    public WidthAndHeightData width(int width) {

        this.width = width;
        return this;
    }

    /**
     * Get width
     * minimum: 0
     *
     * @return width
     **/
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_WIDTH)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public int getWidth() {
        return width;
    }


    @JsonProperty(JSON_PROPERTY_WIDTH)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setWidth(int width) {
        this.width = width;
    }


    public WidthAndHeightData height(int height) {

        this.height = height;
        return this;
    }

    /**
     * Get height
     * minimum: 0
     *
     * @return height
     **/
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_HEIGHT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public int getHeight() {
        return height;
    }


    @JsonProperty(JSON_PROPERTY_HEIGHT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setHeight(int height) {
        this.height = height;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        WidthAndHeightData widthAndHeight = (WidthAndHeightData) o;
        return Objects.equals(this.width, widthAndHeight.width) &&
                Objects.equals(this.height, widthAndHeight.height);
    }

    @Override
    public int hashCode() {
        return Objects.hash(width, height);
    }

    @Override
    public String toString() {
        String sb = "class WidthAndHeightData {\n" +
                "    width: " + toIndentedString(width) + "\n" +
                "    height: " + toIndentedString(height) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public WidthAndHeightData copy() {
        return Cloner.INSTANCE.clone(this);
    }

    @Mapper(mappingControl = DeepClone.class)
    public interface Cloner {
        Cloner INSTANCE = Mappers.getMapper(Cloner.class);

        WidthAndHeightData clone(WidthAndHeightData source);


    }

}

