/*
 * Fake API
 * Just here to generate model of the quercus engine
 *
 * The version of the OpenAPI document: 2022.08.15
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package fr.thalweg.engine.infra.schema.task;

import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import lombok.Getter;
import lombok.Setter;

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = true)
@JsonSubTypes({
        @JsonSubTypes.Type(value = ChangeCursorTask.class, name = "CHANGE_CURSOR"),
        @JsonSubTypes.Type(value = LogTask.class, name = "LOG")

})
@Getter
@Setter
public abstract class AbstractTask {

    protected TaskTypeEnum type;

    public abstract boolean work(float deltaTime);
}

