package fr.thalweg.engine.infra.schema.task;

import com.badlogic.gdx.Gdx;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@JsonIgnoreProperties(
        value = "action", // ignore manually set action, it will be automatically generated by Jackson during serialization
        allowSetters = true // allows the action to be set during deserialization
)
@NoArgsConstructor
public class LogTask extends AbstractTask {

    @JsonProperty
    private String message;

    @Override
    public boolean work(float deltaTime) {
        Gdx.app.log("LogTask", message);
        return true;
    }
}
