configs:
  - name: default
    size: 28
    source: font/Perfect DOS VGA 437 Win.ttf
  # This font will be removed just here for test purpose
  - name: square
    size: 28
    source: font/FORCED SQUARE.ttf